version: "3"
services:
  web:
    build: .
    command: bash -c "alembic init app/alembic && alembic -c app/alembic.ini upgrade head && python3 app/main.py"
    volumes:
      - .:/app
    ports:
      - 8080:8080
    networks:
      - lvlup
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db1
      - POSTGRES_HOST=localhost
    ports:
      - 5432:5433
    networks:
      - lvlup
    hostname: postgres

networks:
  lvlup: