"""Add column comment2.

Revision ID: 2255a754379c
Revises: a511d085ddc9
Create Date: 2023-03-03 21:30:33.366364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2255a754379c'
down_revision = 'a511d085ddc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('comment2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'comment2')
    # ### end Alembic commands ###
