"""Add column comment.

Revision ID: a511d085ddc9
Revises: 0c6ade2f91ed
Create Date: 2023-03-03 21:28:21.095618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a511d085ddc9'
down_revision = '0c6ade2f91ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'comment')
    # ### end Alembic commands ###
